### ISSUE TITLE
ESP32 compling error

### ISSUE THREAD

**Issue by forna91** [DanielVanNoord/AlpacaDiscoveryTests#3]
C:\Users\STEFAN~1\AppData\Local\Temp\arduino_modified_sketch_479418\AsyncUDPClient.ino: In function 'void CheckForDiscovery()':

AsyncUDPClient:84:23: error: invalid conversion from 'char*' to 'uint8_t {aka unsigned char}' [-fpermissive]

     Udp.write(response);

                       ^

In file included from C:\Users\stefanomartini\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi\src/WiFi.h:39:0,

                 from C:\Users\STEFAN~1\AppData\Local\Temp\arduino_modified_sketch_479418\AsyncUDPClient.ino:1:

C:\Users\stefanomartini\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi\src/WiFiUdp.h:64:10: note:   initializing argument 1 of 'virtual size_t WiFiUDP::write(uint8_t)'

   size_t write(uint8_t);

          ^

Più di una libreria trovata per "WiFi.h"
Usata: C:\Users\stefanomartini\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi
Non usata: C:\Program Files (x86)\Arduino\libraries\WiFi
exit status 1
invalid conversion from 'char*' to 'uint8_t {aka unsigned char}' [-fpermissive]

any solution?

**Comment by DanielVanNoord** [comment]
@forna91 I am going to need more information to help you with this. AsyncUDPClient is not part of this repository, are you trying to modify an outside project?
Can you post a complete minimal example, the ino file or link to the source? Also can you tell me the board, board manager, and Arduino ide version you are trying to target?

**Comment by DanielVanNoord** [comment]
@forna91 I have added an ESP32 example using arduino-esp32. You can find it here: https://github.com/DanielVanNoord/AlpacaDiscoveryTests/blob/master/Arduino/ESP32/ESP32.ino. Does that example work better for your board / project?

**Comment by DanielVanNoord** [comment]
Repository now has an example for arduino-esp32

**Comment by forna91** [comment]
Thank you so much!
This is a tester so is ok but for alpaca documentato you have just take care about "alpacadiscovery" string, i should ignore the 1 that is the version of the protocol.
Thanks a lot
